### ISSUE TITLE
Populating issues and pull requests?

### ISSUE THREAD

**Issue by nuthinking** [brianlovin/figma-github-data#10]
Maybe the data has to be static 🤷‍♂️

**Comment by brianlovin** [comment]
Definitely possible, just couldn't be on a private repo as we don't have auth

**Comment by nuthinking** [comment]
Sure, we can just pick https://github.com/microsoft/vscode

Do you want a PR?

**Comment by brianlovin** [comment]
Yeah, if you wanna tackle this that'd be great! We could grab some random issues/PRs from `/withspectrum/spectrum`, `/Facebook/react` etc
