### ISSUE TITLE
Webpack inline source plugin 3.2.0 -> 4.0.0 bump breaks plugin

### ISSUE THREAD

**Issue by eliasjulian** [brianlovin/figma-github-data#40]
Hey Brian! 👋

It looks like the PR from a a few days ago that [bumps webpack from 3.2.0 to 4.0.0](https://github.com/brianlovin/figma-github-data/pull/39) is breaking the plugin when I try to `yarn run build:watch`. I get `TypeError: Cannot read property 'tapAsync' of undefined` and then a `error Command failed with exit code 1.`

I was able to fix it locally and get it running by reverting back to 3.2.0 in `package.json`

Not sure what's actually behind the error or why webpack is being finicky, just wanted to make you aware of it! 

_edit: the plugin successfully builds and I can run it & see the UI in Figma but it's not actually functioning & populating data as expected_

**Comment by brianlovin** [comment]
Hm, that's a bummer! Would you be up for opening a PR to revert that?

**Comment by eliasjulian** [comment]
For sure! Still trying to debug why it's not actually populating data as expected, but I suspect it's also something related to webpack. As soon as I figure that out I can open up a PR.

**Comment by eliasjulian** [comment]
Hey! I'm curious if you can get the plugin successfully working and populating data locally for you? 

I'm having a tough time debugging his because I can get it to successfully build with some changes to the Webpack config, but it's not populating layers with data in Figma. And after trying a few times I hit the rate limit 403 + a CORS error that says `Access to fetch at 'https://api.github.com/users/eliperkins' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

the api user link is unique with every console error (i.e. /eliperkins /emberjs /overleaf) so I know it's calling the right path to the api, but for some reason it's not able to update the node with that content

**Comment by eliasjulian** [comment]
not sure if it's causing this issue, but it looks like `webpack-inline-source-plugin` [is no longer maintained](https://github.com/DustinJackson/html-webpack-inline-source-plugin) in favor of a [similar plugin that Facebook provides](https://github.com/facebook/create-react-app/blob/edc671eeea6b7d26ac3f1eb2050e50f75cf9ad5d/packages/react-dev-utils/InlineChunkHtmlPlugin.js#L10) as of yesterday
