### ISSUE TITLE
When populating by selecting the grandparent of a list of items to populate, all grandchildren get the same value

### ISSUE THREAD

**Issue by nuthinking** [brianlovin/figma-github-data#96]
![Frame 35](https://user-images.githubusercontent.com/163635/82673952-e01d1b80-9c42-11ea-906d-c4b53e7b21de.png)

Tested [here](https://www.figma.com/file/9Y1r5LrZYgcfB7Q1DOCsxw/GitHub-Data-Plugin?node-id=134%3A12).

Not sure 100% about the solution, but it would be nice to support this.

**Comment by nuthinking** [comment]
Selecting **Parent** works as expected, selecting **Grandparent** no.

![Screenshot 2020-05-22 at 15 44 42](https://user-images.githubusercontent.com/163635/82674189-38ecb400-9c43-11ea-9bf6-4c19188f5c6f.png)

**Comment by brianlovin** [comment]
Definitely a bug, that's strange - it should go _per frame_ that is asking for data.

**Comment by nuthinking** [comment]
This should be fixed with #100

**Comment by brianlovin** [comment]
Closed in #100
